openapi: 3.0.0
info:
  title: Dexory API
  description: A basic API
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Dev testing server
  - url: http://localhost:6000
    description: Production build server
paths:
  /test:
    get:
      summary: Returns a number
      description: test endpoint
      responses:
        '200':    # status code
          description: A number
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/test"
components:
  schemas:
    test:
      type: integer
    