/* tslint:disable */
/* eslint-disable */
/**
 * Dexory API
 * Dexory platform api for warehouse tracking
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationScan } from './LocationScan';
import {
    LocationScanFromJSON,
    LocationScanFromJSONTyped,
    LocationScanToJSON,
} from './LocationScan';

/**
 * 
 * @export
 * @interface NamedMachineReport
 */
export interface NamedMachineReport {
    /**
     * 
     * @type {string}
     * @memberof NamedMachineReport
     */
    reportName: string;
    /**
     * 
     * @type {Array<LocationScan>}
     * @memberof NamedMachineReport
     */
    report: Array<LocationScan>;
}

/**
 * Check if a given object implements the NamedMachineReport interface.
 */
export function instanceOfNamedMachineReport(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reportName" in value;
    isInstance = isInstance && "report" in value;

    return isInstance;
}

export function NamedMachineReportFromJSON(json: any): NamedMachineReport {
    return NamedMachineReportFromJSONTyped(json, false);
}

export function NamedMachineReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamedMachineReport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reportName': json['report_name'],
        'report': ((json['report'] as Array<any>).map(LocationScanFromJSON)),
    };
}

export function NamedMachineReportToJSON(value?: NamedMachineReport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'report_name': value.reportName,
        'report': ((value.report as Array<any>).map(LocationScanToJSON)),
    };
}

